apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    volume: website-data
  name: website-data
  namespace: watheia
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
status: {}
